### ISSUE TITLE
MLIR-to-LLVM-IR translation failed because 'btor.nd_state' is unknown

### ISSUE THREAD

**Issue by Po-Chun-Chien** [agurfinkel/btor2mlir#38]
I ran the below commands (following the instructions in [README](https://github.com/agurfinkel/btor2mlir/blob/6feb6ad651f1dfc86f740a0f0e155729e9560a94/README.md))
to translate the Btor2 circuit [noninitstate.btor2](https://github.com/Boolector/btor2tools/blob/8775f9ad9caed51d3daa30a416b1a94dfec532b0/examples/btorsim/noninitstate.btor2) to an LLVM-IR program.
A docker image built from commit 6feb6ad6 was used.

1. `build/bin/btor2mlir-translate --import-btor noninitstate.btor2 > noninitstate.mlir`
2. `build/bin/btor2mlir-opt  --convert-std-to-llvm --convert-btor-to-llvm noninitstate.mlir > noninitstate.mlir.opt`
3. `build/bin/btor2mlir-translate --mlir-to-llvmir noninitstate.mlir.opt > noninitstate.ll`

The first 2 steps succeeded, but the 3rd one failed with the error message:

```
noninitstate.mlir.opt:6:10: error: custom op 'btor.nd_state' is unknown
    %0 = btor.nd_state 0 : !btor.bv<1>
         ^
```

Should I specify any additional command-line arguments to `btor2mlir-translate` or `btor2mlir-opt` to make the translation work?
Or the translation of non-initialized states in Btor2 to LLVM-IR is currently not supported?

**Comment by jetafese** [comment]
Same response as #37 since the same pass handles both inputs and non-deterministically assigned states :)
