### ISSUE TITLE
MLIR-to-LLVM-IR translation failed due to unregistered dialect

### ISSUE THREAD

**Issue by Po-Chun-Chien** [agurfinkel/btor2mlir#39]
I ran the below commands (following the instructions in [README](https://github.com/agurfinkel/btor2mlir/blob/6feb6ad651f1dfc86f740a0f0e155729e9560a94/README.md))
to translate the Btor2 circuit [simple-stack-pred1.btor2](https://github.com/user-attachments/files/15567221/simple-stack-pred1.btor2.gz) (obtained from [HWMCC 2020 benchmark set](http://fmv.jku.at/hwmcc20/hwmcc20benchmarks.tar.xz)) to an LLVM-IR program.
A docker image built from commit 6feb6ad6 was used.

1. `build/bin/btor2mlir-translate --import-btor simple-stack-pred1.btor2 > simple-stack-pred1.mlir`
2. `build/bin/btor2mlir-opt  --convert-std-to-llvm --convert-btor-to-llvm simple-stack-pred1.mlir > simple-stack-pred1.mlir.opt`
3. `build/bin/btor2mlir-translate --mlir-to-llvmir simple-stack-pred1.mlir.opt > simple-stack-pred1.ll`

The first 2 steps succeeded, but the 3rd one failed with the error message:

```
simple-stack-pred1.mlir.opt:9:63: error: `!"btor"<"bv<32>">` type created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used
    %3 = builtin.unrealized_conversion_cast %2 : i32 to !btor.bv<32>
                                                              ^
```

I added `-allow-unregistered-dialect` to the 2nd command as the error message suggested,
but the same error persisted.

Should I specify any additional command-line arguments to `btor2mlir-translate` or `btor2mlir-opt` to make the translation work?
Or are there any specific Btor2 features in this example that are currently not supported?

**Comment by jetafese** [comment]
Do you get the same issue with the main branch here? https://github.com/jetafese/btor2mlir

For the record, the main development happens in the linked repository

**Comment by Po-Chun-Chien** [comment]
Yes, the same issue also exists in at the latest commit (345625097) in the development [fork](https://github.com/jetafese/btor2mlir).

When running the second command (with `-allow-unregistered-dialect`), I see some additional messages:

```
Converting array type to mem cell
Converting array type to llvm struct: !llvm.struct<(ptr<i32>, ptr<i32>, i64, array<1 x i64>, array<1 x i64>)>
```

But the same error happened when running the 3rd command.
